### ISSUE TITLE
Would you like to merge ?

### ISSUE THREAD

**Issue by rmedaer** [lord2800/node-gitolite#1]
Hi @lord2800 ,

FYI I made the same kind of library [here](https://github.com/Slidesk/node-gitolite). Would you like to merge our repositories and then use only one NPM name ?

Let me know if you have suggestions or other advices.

Have a good day,

**Comment by lord2800** [comment]
I ended up abandoning this and using the gitlab API instead.

**Comment by rmedaer** [comment]
Do you think it would be possible to transfer NPM name `node-gitolite` to my repository ?

Thank's in advance,

**Comment by lord2800** [comment]
Sure.

**Comment by lord2800** [comment]
I added you as an owner--feel free to remove me once you've made sure you're able to access things.

**Comment by rmedaer** [comment]
Nice. Thank you very much. :-)
